name: End-to-end tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run docker-compose
              run: docker-compose up --exit-code-from cypress

            
